[2025-04-14T10:50:21.158+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_task.print_welcome scheduled__2025-04-12T23:00:00+00:00 [queued]>
[2025-04-14T10:50:21.200+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_task.print_welcome scheduled__2025-04-12T23:00:00+00:00 [queued]>
[2025-04-14T10:50:21.201+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-14T10:50:21.250+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_welcome> on 2025-04-12 23:00:00+00:00
[2025-04-14T10:50:21.254+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2025-04-14T10:50:21.260+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_task', 'print_welcome', 'scheduled__2025-04-12T23:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_task.py', '--cfg-path', '/tmp/tmpo3j6zlmj']
[2025-04-14T10:50:21.262+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask print_welcome
[2025-04-14T10:50:21.492+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_task.print_welcome scheduled__2025-04-12T23:00:00+00:00 [running]> on host bb379e170722
[2025-04-14T10:50:21.811+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_task' AIRFLOW_CTX_TASK_ID='print_welcome' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-12T23:00:00+00:00'
[2025-04-14T10:50:21.814+0000] {logging_mixin.py:188} INFO - Welcome to Airflow!
[2025-04-14T10:50:21.815+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-14T10:50:21.833+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_task, task_id=print_welcome, execution_date=20250412T230000, start_date=20250414T105021, end_date=20250414T105021
[2025-04-14T10:50:21.916+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-14T10:50:21.974+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
